#!/bin/bash
clear
echo -e "\e[1m\e[33m    A long time ago in a galaxy far, far away....\e[0m"
sleep 2
clear
echo -e "\e[31m
                .-^-.-^-.
               /_/_\_/_\
            .'.'._.'.'._.'.
           /_/_\_/_\_/_\_\
          .'.'._.'.'._.'._.'.
         /_/_\_/_\_/_\_/_\_\
        .'.'._.'.'._.'._.'._.'.
       /_/_\_/_\_/_\_/_\_/_\_\
           |  O (_) O  |
           |___________|
            \_         _/
             '._   _.'
                \_/
\e[0m"
sleep 2
clear
echo -e "\e[1m\e[33m    It is a period of civil war.
    Rebel spaceships, striking
    from a hidden base, have won
    their first victory against
    the evil Galactic Empire.\e[0m"
sleep 4
clear
echo -e "\e[1m\e[33m    During the battle, Rebel spies
    managed to steal secret plans
    to the Empire's ultimate weapon,
    the DEATH STAR, an armored
    space station with enough
    power to destroy an entire planet.\e[0m"
sleep 4
clear
echo -e "\e[1m\e[33m    Pursued by the Empire's sinister
    agents, Princess Leia races
    home aboard her starship,
    custodian of the stolen plans
    that can save her people and
    restore freedom to the galaxy....\e[0m"
sleep 4
clear
echo -e "\e[31m
                .-^-.-^-.
               /_/_\_/_\
            .'.'._.'.'._.'.
           /_/_\_/_\_/_\_\
          .'.'._.'.'._.'._.'.
         /_/_\_/_\_/_\_/_\_\
        .'.'._.'.'._.'._.'._.'.
       /_/_\_/_\_/_\_/_\_/_\_\
           |  O (_) O  |
           |___________|
            \_         _/
             '._   _.'
                \_/
\e[0m"
sleep 2
clear

